### PR TITLE
Features/continuous integration

### PR DESCRIPTION
**Pull request by cidermole**
* mmt update: Update from git and compile complete MMT system from sources (for developers)
* mmt batch: Batch-translate corpora in a directory and output into dest directory DEST
* mmt sweep: Parameter sweep: repeatedly translate a test set with different params

some fun stuff for system development. Uli asked me to build these basic blocks, mostly for continuous integration testing.

### CODE REVIEW

**Comment by cidermole** [comment]
The coolest feature is probably parameter sweeps. This currently runs only on a local node, since it needs a regular engine restart.

```
$ ./mmt sweep --param suffixarrays.sample "10 20 50" --param lm.alpha "0.3 0.9" 
suffixarrays.sample     lm.alpha        bleu
10      0.3     44.33
10      0.9     44.56
20      0.3     45.17
20      0.9     45.39
50      0.3     46.43
50      0.9     46.79
```

**Comment by cattoni** [comment]
very cool!

**Comment by davidecaroselli** [comment]
@cidermole thanks for you work, but some of the design decisions in this pull request are in contrast with the design of the MMT command line interface.
Scripts and command for developers cannot be added to the simple-user command line.

One of the main goal of MMT is to keep the product as simple as possible, giving much importance to the UX of the product.

For this reason I have to revert the merge of the pull request. We will redesign some of the commands you have implemented in order to complete a second merge.

As a rule of thumb: every modification of a component that is directly exposed to the user must be  discussed and agreed in advance, the command line interface is in fact one of these components.

Thanks you,
Davide

**Comment by cidermole** [comment]
OK, should have waited for your merge, just didn't realize you were back from holidays :)

**Pull request merged**
